name = "iekei-remix"
type = "javascript"

zone_id = ""
account_id = ""
route = ""
workers_dev = true

kv_namespaces = [
  { binding = "IEKEI", id = "", preview_id = "" }
]

[vars]
X_MICROCMS_API_KEY = ""
X_MICROCMS_WEBHOOK_SECRET = ""

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build"

[build.upload]
format="service-worker"
